spring.application.name=counterparty-report
# ??????
server.port=8080

# ???? ?????? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/counterparty_db
spring.datasource.username=postgres
spring.datasource.password=antonuch25
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# DaData API (???? ??????? ? ?????????? ?????????)
dadata.api.url=https://suggestions.dadata.ru/suggestions/api/4_1/rs/findById/party
dadata.api.token=${DADATA_API_TOKEN}